# Generated by Django 5.0.1 on 2024-06-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_profile_pic_alter_portfolio_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
