# Generated by Django 5.0.1 on 2024-06-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='cond',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
