# Generated by Django 5.0.1 on 2024-06-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_template_cond'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
