# Generated by Django 5.0.1 on 2024-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_template_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='uploads/projects/'),
        ),
    ]
