# Generated by Django 5.0.1 on 2024-08-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfolio_gender_alter_portfolio_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_pic',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='screenshot',
            field=models.URLField(blank=True, null=True),
        ),
    ]
